# IF YOU DO NOT KNOW WHAT THIS FILE IS IGNORE IT
title_name = "Rock Band"
title_id = "45410829"
hash = "42054E24EA901110" # default.xex

[[patch]]
    name = "cymbals or whatever"
    author = "Synchrony"
    is_enabled = true

    # if gem is in phrase just set 7 to a probably unused register ~_~
    [[patch.be32]]
        address = 0x8283d64c
        value   = 0x3bc00007    # li r30,0x7
    [[patch.be32]]
        address = 0x8283d650
        value   = 0x42800018    # b 0x8283d668

    # when branching to normal
    [[patch.be32]]
        address = 0x8283d6cc
        value   = 0x480632cd    # bl 0x828a0998

    # load normal
    [[patch.be32]]
        address = 0x828a0998
        value   = 0x81700000    # lwz r11,0x0(r16)

    # check if r30 isn't 7
    [[patch.be32]]
        address = 0x828a099c
        value   = 0x2c1e0007    # cmpwi r30,0x7
    [[patch.be32]]
        address = 0x828a09a0
        value   = 0x4082000c    # bne 0x828a09ac

    # load star
    [[patch.be32]]
        address = 0x828a09a4
        value   = 0x81720000    # lwz r11,0x0(r18)
    [[patch.be32]]
        address = 0x828a09a8
        value   = 0x3bc00000    # li r30, 0x0

    [[patch.be32]]
        address = 0x828a09ac
        value   = 0x4e800020    # blr


    # when branching to tom
    [[patch.be32]]
        address = 0x8283d6c4
        value   = 0x480632ed    # bl 0x828a09b0

    # load tom
    [[patch.be32]]
        address = 0x828a09b0
        value   = 0x81740000    # lwz r11,0x0(r20)

    # check if r30 isn't 7
    [[patch.be32]]
        address = 0x828a09b4
        value   = 0x2c1e0007    # cmpwi r30,0x7
    [[patch.be32]]
        address = 0x828a09b8
        value   = 0x4082000c    # bne 0x828a09c4

    # load unison
    [[patch.be32]]
        address = 0x828a09bc
        value   = 0x81730000    # lwz r11,0x0(r19)
    [[patch.be32]]
        address = 0x828a09c0
        value   = 0x3bc00000    # li r30, 0x0

    [[patch.be32]]
        address = 0x828a09c4
        value   = 0x4e800020    # blr
[[patch]]
    name = "disable texture compression"    # not applied to the xex!
    author = "Synchrony"
    is_enabled = true

    [[patch.be32]]
        address = 0x822eb398    # CompositeCharacter::CompressTextures according to rb2 wii
        value   = 0x4e800020    # blr
[[patch]]
    name = "dont reset shared songs on event set"
    author = "Synchrony"
    is_enabled = true

    [[patch.be32]]
        address = 0x823e8ec4    # call to SongMgr::ResetSharedSongs in BaseTourPerformer::SetEvent
        value   = 0x60000000    # nop

[[patch]]
    name = "song_mgr get_data"
    author = "Synchrony"
    is_enabled = true

    [[patch.string]]
        address = 0x8207c158
        value   = "get_data"    # overwrite has_song name

    [[patch.be32]]
        address = 0x8244e144    # kinda end of inlined SongMgr:HasSong in SongMgr:Handle (every SongMgr:Data call is inlined too. fuck this compiler!)
        value   = 0x48452884    # b 0x828a09c8

    # done like this because of all the stupid compiler tricks. there's almost enough room not to :(
    [[patch.be32]]
        address = 0x828a09c8
        value   = 0x7c6b1b78    # or r11,r3,r3
    [[patch.be32]]
        address = 0x828a09cc
        value   = 0x3940000a    # li r10,0xa (set return type to kDataArray)
    [[patch.be32]]
        address = 0x828a09d0
        value   = 0x915c0004    # stw r10,0x4(r28)
    [[patch.be32]]
        address = 0x828a09d4
        value   = 0x4BBAD780    # b 0x8244e154

[[patch]]
    name = "update cache name"
    author = "Synchrony"
    is_enabled = true

    [[patch.string]]
        address = 0x8207c528
        value   = "rb1uwucache"

[[patch]]
    name = "dont reset shared songs on get_local_unlocked_songs"
    author = "Synchrony"
    is_enabled = true

    [[patch.be32]]
        address = 0x8244dba0 # call to SongMgr::ResetSharedSongs in SongMgr::OnGetLocalUnlockedSongs
        value   = 0x60000000 # nop