name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - name: Set env
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Build ARK
        run: |
          python _build_xbox.py
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: RB1U-Xbox
          path: _build/xbox

  build_ps3_usa:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - name: Build ARK
        run: |
          python _build_ps3.py
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP0006-BLUS30050_00-RB1UALPHA"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v6
        with:
          name: RB1U-PS3-USA
          path: '*.pkg'

